Add components; Add css
ps99/reactjs-gmp pull request #1
Opened 2022-10-27 08:07 UTC by ps99

- [x]  - Markup is done with React Components and React Fragments (parent-child)
- [x] - Apply styles (no need to do pixel perfect and strict colors following)
- [ ] - Use PropTypes
- [ ] - Use [<ErrorBoundary />](http://reactjs.org/docs/error-boundaries.html) component for catching and displaying errors

2022-10-27 13:42 UTC, mikita-syradoyeu-epam commented on src/components/Main/Main.tsx
> +  const moviesItems = movies.map((item:any, i:number) => {
It's look like separate component

2022-10-27 13:42 UTC, mikita-syradoyeu-epam commented on src/components/Main/Main.tsx
> +          <div className="movie-item__date">2004</div>
Why do you use static data if you have all this data in your movie array?

2022-10-27 13:42 UTC, mikita-syradoyeu-epam commented on src/scss/base/_common.scss
> +*, *::before, *::after {
Please use styled components and store the styles file in the component folder

2022-10-27 13:45 UTC, ps99 commented on src/components/Main/Main.tsx
> +          <div className="movie-item__date">2004</div>
This part is in progress

2022-11-02 10:06 UTC, ps99 commented on src/components/Footer/Footer.tsx
> +      <a href="/" className="footer-logo"><img src={Logo} alt="NetflixRoulette" /></a>
Updated

2022-11-02 10:06 UTC, ps99 commented on src/components/Main/Main.tsx
> +  const naviFilter = filters.map((item:string, i:number) => {
Fixed

2022-11-02 10:06 UTC, ps99 commented on src/components/Main/Main.tsx
> +  const naviSorter = sorts.map((item:string, i:number) => {
Fixed

2022-11-02 10:07 UTC, ps99 commented on src/components/Main/Main.tsx
> +          <div className="movie-item__date">2004</div>
Updated

2022-11-02 10:08 UTC, ps99 commented on src/scss/base/_common.scss
> +*, *::before, *::after {
Started using styled components

2022-11-04 12:54 UTC, mikita-syradoyeu-epam commented
Let's create an assets folder in which we will store a folder with images

2022-11-04 13:38 UTC, mikita-syradoyeu-epam requested changes

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/StyledApp.ts
> +  h2 {
If you want to create universal styles for text tags you can create separate component Typography, which will take props: as, children, variant

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/components/Button/StyledButton.ts
> +const StyledButton = styled.button<{variant: string | undefined}>`
Please, create Type files

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/components/Button/StyledButton.ts
> +    background: #999;
You can create theme file which will contain object with all your colors, font-size and other and use it in ThemeProvider

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/components/Button/index.tsx
> +
You shouldn't have deleted the Button.tsx file. You have to import this file into index.js and export it from there

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/components/Button/index.tsx
> +export interface IButton {
This look like code for Button.type.ts file

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/components/ErrorBoundary/index.tsx
> +  return <>{isEveryThingOk ? props.children : <OopsText />}</>;
isEveryThingOk is rudimental variable as I see

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/components/Footer/index.tsx
> +    <StyledFooter className="footer">
Why you use className here?

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/components/Footer/index.tsx
> +      <a href="/" className="footer-logo">
You also can create Link component with needed styles

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/components/Main/index.tsx
> +      <StyledNav>
I think, we can create separate component here

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/components/Main/Sorter/index.tsx
> +        <i></i>
It looks a little strange

2022-11-04 13:38 UTC, mikita-syradoyeu-epam commented on src/components/Main/Sorter/StyledSorter.ts
> +  i {
You can create separate StyledComponent and it help to understand, what it is. For example <StyledSomeUsefullComponent />

2022-11-04 14:17 UTC, ps99 commented on src/components/Button/index.tsx
> +
Why?

2022-11-04 14:20 UTC, ps99 commented on src/components/Footer/index.tsx
> +      <a href="/" className="footer-logo">
Actually, it's a rudimental class from previous approach

2022-11-15 06:22 UTC, grandmaus commented on src/components/Footer/StyledFooter.ts
> +const StyledFooter = styled.div`
Please use semantic tags

2022-11-15 06:22 UTC, grandmaus commented on src/components/Button/Button.tsx
> +  handler: any;
Avoid `any`

2022-11-15 06:22 UTC, grandmaus commented on src/components/Header/Search/HeaderSearch.tsx
> +  };
Separate return with an empty line

2022-11-15 06:22 UTC, grandmaus commented on src/components/Header/Search/StyledSearch.ts
> +const StyledSearch = styled.div`
`export const`

2022-11-15 06:22 UTC, grandmaus commented on src/shared/theme.ts
> +}
Move this to `common` folder

2022-11-15 06:22 UTC, grandmaus commented on src/components/Header/Search/StyledSearch.ts
> +import * as T from '../../../shared/theme'
`import { color, font }`

2022-11-15 06:22 UTC, grandmaus commented on src/components/Header/StyledHeader.ts
> +  & > button {
Please style the existing component instead

2022-11-15 06:22 UTC, grandmaus commented on src/components/Header/StyledHeader.ts
> +const StyledHeader = styled.header`
`export const`

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/Filter/Filter.tsx
> +        key={i}
https://reactjs.org/docs/lists-and-keys.html#keys

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/Filter/Filter.tsx
> +import * as I from "./Filter.type";
`import { IFilter }`

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/Filter/Filter.type.ts
> +  filtersList: string[];
Use `ReadonlyArray` or `Array` instead of `[]`

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/Filter/Filter.type.ts
> +  onGenreClick: any;
Avoid `any`

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/MainPage.tsx
> +const json_data = ((data: any): I.IMoviesListItem[] => {
Why snake_case?

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/MainPage.tsx
> +          }
Move to separate function

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/MainPage.tsx
> +          }
Same

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/MoviesList/StyledMoviesList.ts
> +  & > li {
Use styled component instead

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/MoviesList/StyledMoviesList.ts
> +  h2 {
Use styled component instead

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/MoviesList/StyledMoviesList.ts
> +  span {
Use styled component instead

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/Sorter/StyledSorter.ts
> +width: 260px;
Formatting

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/Sorter/StyledSorter.ts
> +export const StyledArrow = styled.i`
I think it might be a pseudo element

2022-11-15 06:22 UTC, grandmaus commented on src/components/Pages/MainPage/Sorter/StyledSorter.ts
> +  content: ' Date';
Formatting

2022-11-16 20:47 UTC, ps99 commented on src/components/Pages/MainPage/Sorter/StyledSorter.ts
> +export const StyledArrow = styled.i`
Disagree

2022-11-16 20:50 UTC, ps99 commented on src/components/ErrorBoundary/index.tsx
> +const ErrorBoundary = (props: any) => {
No idea how to fix it

2022-11-16 20:52 UTC, ps99 commented on src/components/Pages/MainPage/MoviesList/StyledMoviesList.ts
> +  h2 {
why? It just simple `h2`. I don't need and don't want to have element with extra class.

2022-11-16 22:06 UTC, ps99 commented on src/components/Footer/Footer.tsx
> +import Logo from "../../assets/images/header-logo.svg";
What do you mean?

2022-11-18 22:13 UTC, ps99 commented on src/components/Header/StyledHeader.ts
> +  & > button {
?

2022-11-18 22:18 UTC, ps99 commented on src/components/Pages/MainPage/MainPage.tsx
> +const json_data = ((data: any): I.IMoviesListItem[] => {
just because it's a temporary data

2022-11-18 22:29 UTC, ps99 commented on src/components/Pages/MainPage/MoviesList/StyledMoviesList.ts
> +  & > li {
Is it really better?

2022-11-20 21:15 UTC, merged